config/routes.rb
Rails.application.routes.draw do
  resources :regions
  resources :municipalities
  root to: 'visitors#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/municipality.rb
class Municipality < ApplicationRecord

  has_and_belongs_to_many :regions

  validates :name, presence: true
  validates :numeric_code, presence: true
  validates :numeric_code, uniqueness: true

  after_update :check_state

  def get_state
    state ? 'Activo' : 'Inactivo'
  end

  private

  def check_state
    unless state
      Region.all.each do |region|
        region.municipalities.delete(self)
      end
    end
  end
  
end

app/models/region.rb
class Region < ApplicationRecord

  has_and_belongs_to_many :municipalities

  validates :name, presence: true
  validates :numeric_code, presence: true
  validates :numeric_code, uniqueness: true

  def update_municipalities(new_municipalities)
    new_municipalities.each{|m| municipalities << m unless municipalities.include?(m) }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/municipalities_controller.rb
class MunicipalitiesController < ApplicationController
  before_action :set_municipality, only: [:show, :edit, :update, :destroy]

  def index
    @municipalities = Municipality.all
  end

  def show
  end

  def new
    @municipality = Municipality.new
  end

  def edit
  end

  def create
    @municipality = Municipality.new(municipality_params)

    if @municipality.save
      redirect_to municipalities_url, notice: 'Municipio creado correctamente.'
    else
      render :new
    end
  end

  def update
    if @municipality.update(municipality_params)
      redirect_to municipalities_url, notice: 'Municipio actualizado correctamente.'
    else
      render :edit
    end
  end

  def destroy
    @municipality.destroy
    redirect_to municipalities_url, notice: 'Municipio eliminado correctamente.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipality
      @municipality = Municipality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def municipality_params
      params.require(:municipality).permit(:numeric_code, :name, :state)
    end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  before_action :set_region, only: [:show, :edit, :update, :destroy]
  before_action :set_municipalities, only: [:create, :update]

  def index
    @regions = Region.all
  end

  def show
  end

  def new
    @region = Region.new
  end

  def edit
  end

  def create
    @region = Region.new(region_params)

    if @region.save
      @region.municipalities << @municipalities
      redirect_to regions_url, notice: 'Región creada correctamente.'
    else
      render :new
    end
  end

  def update
    if @region.update(region_params)
      @region.update_municipalities(@municipalities)
      redirect_to regions_url, notice: 'Región actualizada correctamente.'
    else
      render :edit
    end
  end

  def destroy
    @region.destroy
    redirect_to regions_url, notice: 'Región eliminada correctamente.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_region
      @region = Region.find(params[:id])
    end

    def set_municipalities
      @municipalities = Municipality.find(params[:region][:municipalities].select(&:present?))
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def region_params
      params.require(:region).permit(:numeric_code, :name)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper

  def municipalities_names(region)
    region.municipalities.collect(&:name).join(',')
  end

  def regions_names(municipality)
    municipality.regions.collect(&:name).join(',')
  end

end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 4.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}", :role  => "alert"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
.container
  %nav.navbar.navbar-dark.bg-inverse
    %ul.nav.navbar-nav.clearfix
      %li.nav-item
        %button.navbar-toggler.hidden-sm-up.nav-link{"aria-controls" => "exCollapsingNavbar2", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#exCollapsingNavbar2", "data-toggle" => "collapse", :type => "button"}
          \ &#9776;
    #exCollapsingNavbar2.collapse.navbar-toggleable-xs
      = link_to "Rails bootstrap", root_path, class: 'navbar-brand'
      %ul.nav.navbar-nav= render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}
    
    %title REGIONES Y MUNICIPIONS
    
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
    = csrf_meta_tags

  %body
    %nav.navbar.navbar-expand-md.navbar-dark.bg-dark.fixed-top
      %a.navbar-brand{:href => root_path} INICIO
      %button.navbar-toggler{"aria-controls" => "navbarsExampleDefault", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarsExampleDefault", "data-toggle" => "collapse", :type => "button"}
        %span.navbar-toggler-icon
      #navbarsExampleDefault.collapse.navbar-collapse
        %ul.navbar-nav.mr-auto
          %li.nav-item.active
            %a.nav-link{:href => regions_path} REGIONES
          %li.nav-item.active
            %a.nav-link{:href => municipalities_path} MUNICIPIOS
    %main.container{:role => "main"}
      %p#notice= notice
      = yield

app/views/municipalities/_form.html.haml
= form_for @municipality, class: 'form' do |f|
  - if @municipality.errors.any?
    #error_explanation
      %h2= "#{pluralize(@municipality.errors.count, "error")} prohibited this municipality from being saved:"
      %ul
        - @municipality.errors.full_messages.each do |message|
          %li= message

  .form-group.row
    = f.label 'Código', class: 'label col-sm-1'
    = f.number_field :numeric_code, class: 'form-control col-sm-4', required: true
  
  .form-group.row
    = f.label 'Nombre', class: 'label col-sm-1'
    = f.text_field :name, class: 'form-control col-sm-4', required: true
  
  .form-group.row
    = f.label 'Estado', class: 'label col-sm-1'
    = f.check_box :state, class: 'form-control col-sm-4'
  
  .actions
    = f.submit 'Guardar', class: 'btn btn-success btn-sm'

app/views/municipalities/edit.html.haml
%h3 EDITAR MUNICIPIO

= render 'form'
%hr
= link_to 'Volver', municipalities_path

app/views/municipalities/index.html.haml
%h3 MUNICIPIOS

%table.table.table-bordered.table-sm
  %thead
    %tr
      %th CÓDIGO
      %th NOMBRE
      %th ESTADO
      %th REGIONES
      %th{colspan: 3} OPCIONES

  %tbody
    - @municipalities.each do |municipality|
      %tr
        %td= municipality.numeric_code
        %td= municipality.name
        %td= municipality.get_state
        %td
          - municipality.regions.each do |region|
            = link_to region.name, region, class: 'btn btn-primary btn-sm'
        %td= link_to 'Ver', municipality
        %td= link_to 'Editar', edit_municipality_path(municipality)
        %td= link_to 'Eliminar', municipality, method: :delete, data: { confirm: 'Está seguro?' }

%br

= link_to 'Nuevo Municipio', new_municipality_path, class: 'btn btn-success btn-sm'

app/views/municipalities/new.html.haml
%h3 NUEVO MUNICIPIO

= render 'form'
%hr
= link_to 'Volver', municipalities_path

app/views/municipalities/show.html.haml
%h3 MUNICIPIO

%p
  %b Código:
  = @municipality.numeric_code
%p
  %b Nombre:
  = @municipality.name
%p
  %b Estado:
  = @municipality.get_state
%p
  %b Regiones:
  = regions_names(@municipality)

%hr
= link_to 'Edit', edit_municipality_path(@municipality)
= link_to 'Volver', municipalities_path

app/views/regions/_form.html.haml
= form_for @region, class: 'form' do |f|
  - if @region.errors.any?
    #error_explanation
      %h2= "#{pluralize(@region.errors.count, "error")} prohibited this region from being saved:"
      %ul
        - @region.errors.full_messages.each do |message|
          %li= message

  .form-group.row
    = f.label 'Código', class: 'label col-sm-2'
    = f.number_field :numeric_code, class: 'form-control col-sm-4'
  
  .form-group.row
    = f.label 'Nombre', class: 'label col-sm-2'
    = f.text_field :name, class: 'form-control col-sm-4'

  .form-group.row
    = f.label 'Municipios', class: 'label col-sm-2'
    = f.select :municipalities, Municipality.all.collect {|m| [ m.name, m.id ] }, {}, {class: 'form-control col-sm-4', multiple: true, include_blank: false, selected: [@region.municipalities.collect(&:id)] }
  
  .actions
    = f.submit 'Guardar', class: 'btn btn-success btn-sm'

app/views/regions/edit.html.haml
%h3 EDITAR REGIÓN

= render 'form'
%hr
= link_to 'Volver', regions_path
= link_to 'VER', @region

app/views/regions/index.html.haml
%h3 REGIONES

%table.table.table-bordered.table-sm
  %thead
    %tr
      %th CÓDIGO NUMÉRICO
      %th NOMBRE
      %th MUNICIPIOS
      %th{colspan: 3} OPCIONES

  %tbody
    - @regions.each do |region|
      %tr
        %td= region.numeric_code
        %td= region.name
        %td
          - region.municipalities.each do |m| 
            = link_to m.name, m, class: 'btn btn-primary btn-sm'
        %td= link_to 'Ver', region
        %td= link_to 'Editar', edit_region_path(region)
        %td= link_to 'Eliminar', region, method: :delete, data: { confirm: 'Está seguro?' }

%br

= link_to 'Nueva Región', new_region_path, class: 'btn btn-success btn-sm'

app/views/regions/new.html.haml
%h3 NUEVA REGIÓN

= render 'form'
%hr
= link_to 'Volver', regions_path

app/views/regions/show.html.haml
%h3 REGION

%p
  %b Código:
  = @region.numeric_code
%p
  %b Nombre:
  = @region.name

%p
  %b Municipios:
  = municipalities_names(@region)


%hr
= link_to 'Edit', edit_region_path(@region)
= link_to 'Volver', regions_path

app/views/visitors/index.html.haml
%h3 REGIONES Y MUNICIPIOS

.card{:style => "width: 18rem;"}
  .card-body
    %h5.card-title Prueba Talenta365
    %h6.card-subtitle.mb-2.text-muted Marco Montes
    %p.card-text marcomontes@gmail.com